import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { formatCredits } from "../../../utils/format";
export function UserHeader({ view, balance, userEmail, onNavigate, onLogout, roomMode, onRequestExit }) {
    const effectiveView = view === "stats" ? "stats" : "other";
    const formattedBalance = formatCredits(balance);
    const displayName = userEmail ? userEmail.split("@")[0] : "";
    return (_jsxs("header", { className: "user-topbar", children: [_jsxs("div", { className: "user-brand", children: [_jsx("div", { className: "user-brand__icon", "aria-hidden": "true", children: _jsx("img", { src: "/logo.png", alt: "Dino Bingo", className: "w-10 h-10 object-contain" }) }), _jsxs("div", { children: [_jsx("h1", { className: "user-brand__title", children: "Dino Bingo" }), _jsx("p", { className: "user-brand__subtitle", children: "Tu panel personal" })] })] }), !roomMode && (_jsxs("nav", { className: "user-topnav", "aria-label": "Navegaci\u00F3n principal", children: [_jsx("button", { type: "button", className: `user-topnav__link ${effectiveView === "stats" ? "user-topnav__link--active" : ""}`, onClick: () => onNavigate("stats"), children: "Mis estad\u00EDsticas" }), _jsx("button", { type: "button", className: "user-topnav__link", children: "Ayuda" })] })), _jsxs("div", { className: "user-topnav__right", children: [!roomMode && (_jsxs(_Fragment, { children: [_jsxs("button", { type: "button", className: "user-balance-pill", onClick: () => onNavigate("balance"), children: [_jsx("span", { className: "material-symbols-outlined", "aria-hidden": "true", children: "account_balance_wallet" }), _jsx("span", { className: "user-balance-pill__label", children: formattedBalance })] }), _jsxs("div", { className: "user-profile", children: [_jsx("div", { className: "user-avatar", "aria-hidden": "true" }), displayName && _jsx("span", { className: "user-profile__name", children: displayName })] })] })), _jsxs("button", { type: "button", className: roomMode ? "user-room-exit" : "user-logout", onClick: roomMode && onRequestExit ? onRequestExit : onLogout, children: [_jsx("span", { className: "material-symbols-outlined", "aria-hidden": "true", children: "logout" }), roomMode && _jsx("span", { children: "Salir" })] })] })] }));
}
export default UserHeader;
